[project]
name = "query-builder-widget"
version = "1.0.1"
description = "A small query builder widget for Django."
requires-python = ">=3.13"

dependencies = []

[dependency-groups]
dev = [
    "django>=6.0.6",
    "ruff>=0.15.12",
]

[tool.hatch.build.targets.wheel]
packages = ["query_builder_widget"]

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py313"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
docstring-code-format = true

[tool.ruff.lint]
select = ["E", "F", "I", "W"]
ignore = ["E203"]

[tool.ruff.lint.isort]
known-first-party = ["ballsdex", "bd_models", "settings"]
split-on-trailing-comma = false
